stages:
  - build

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME


build_front:
  stage: build
  image: node:latest
  script:
    - cd Frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./Frontend/dist

build_back:
  image: gradle:alpine
  stage: build
  script: 
    - cd Backend
    - gradle --build-cache assemble
  artifacts:
    paths:
      - ./Backend/build/libs/
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle


